CREATE TABLE USUARIOS (
    USUARIO VARCHAR (50)   NOT NULL,
    CLAVE VARCHAR (8)   NOT NULL,
    PRIMARY KEY (USUARIO)
);

CREATE TABLE PROPIEDADES (
    ID INT (10)   NOT NULL AUTO_INCREMENT,
    GLOSA VARCHAR (250)   NOT NULL,
    TIPO INT (1) NOT NULL,
    ESTADO INT(1) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PROPIEDADES_DET ( 
    ID INT (10) NOT NULL AUTO_INCREMENT, 
    ID_PROPIEDAD INT (10) NOT NULL, 
    DETALLE VARCHAR(2000),
    BANIOS VARCHAR(100),
    DORMITORIOS VARCHAR(2000),
    PRECIO VARCHAR(20),
    DIRECCION VARCHAR(100),
    SECTOR VARCHAR (20),
    COMUNA VARCHAR (5),
    PRIMARY KEY (ID) 
);



CREATE TABLE REGIONES (
    COD_REG VARCHAR (2)   NOT NULL,
    NOMBRE_REG VARCHAR (100)   NOT NULL,
    PRIMARY KEY (COD_REG)
);

CREATE TABLE PROVINCIAS (
    COD_PROV VARCHAR (3) NOT NULL,
    COD_REG VARCHAR (2)   NOT NULL,
    NOMBRE_PROV VARCHAR (50)   NOT NULL,
    PRIMARY KEY (COD_PROV)
);

CREATE TABLE COMUNAS (
    COD_COM VARCHAR (5)   NOT NULL,
    COD_PROV VARCHAR (3) NOT NULL,
    COD_REG VARCHAR (2)   NOT NULL,
    NOM_COM VARCHAR (50)   NOT NULL,
    PRIMARY KEY (COD_COM)
);
